const ServiceData = [
    {
        title: "الكتب",
        description: "أفضل ما يمكن أن تتركه علمٌ وهبه الله لك، والكتاب كلمات من نور تضيء لك ولمن حولك بما وهبك الله من علم أو معلومة صادقة تفيد بها من حولك وتكون أفضل أثر لك في الدنيا والآخرة",
        btnCaption: "طلب عرض سعر",
        btnLink: "servBooks",
        imgSrc: "./images/servBooks-img.jpg",
        imgAlt: "Books services",
        icon: "./images/ico-books.png",
    },
    {
        title: "المواقع والتطبيقات",
        description: "كل مؤسسة يجب أن يكون لديها عنوان على شبكة الإنترنت يبرز نشاطاتها ويتحدث عن أقسامها بكل تفصيل، ولدينا آليات مميزة لتنفيذ موقعك الإلكتروني و تطبيقك ومتجرك بأفضل وأحدث آلية",
        btnCaption: "طلب عرض سعر",
        btnLink: "servWeb",
        imgSrc: "./images/servWeb-img.jpg",
        imgAlt: "Web Applications services",
        icon: "./images/ico-web.png",
    },
    {
        title: "سوشيال ميديا",
        description: "السوشيال ميديا هي لغة العصر في التسويق الإلكتروني وتأثيرها في الإنتشار والوصول إلى العملاء أصبحت شئ أساسي لكل منتج أو فكرة أونشاط، معنا ستجد خطة محددة للنشر والتسويق والوصول لعملاءك وجمهورك المحتمل",
        btnCaption: "طلب عرض سعر",
        btnLink: "servSocial",
        imgSrc: "./images/servSocial-img.jpg",
        imgAlt: "Social media services",
        icon: "./images/ico-social.png",
    },
    {
        title: "الهوية البصرية",
        description: "الهوية جو عام يمثلك من خلال شعار ومجموعة لونية وأشكال متداخلة أو مبسطة تعبر عنك وتكون عنوان لك يعرفُكَ بها كل متلقٍ لها بتطبيقها على العناصر المختلفة",
        btnCaption: "طلب عرض سعر",
        btnLink: "servIdentity",
        imgSrc: "./images/servIdentity-img.jpg",
        imgAlt: "Identity Services",
        icon: "./images/ico-identity.png",
    },
    {
        title: "باكج دعائي",
        description: "تطبيق لهويتك البصرية على أوراقك الرسمية (ورق مكاتبات - فواتير - إذن صرف - إذن استلام - ختم - كروت) حدد المطلوب ويشرفنا التنفيذ",
        btnCaption: "طلب عرض سعر",
        btnLink: "servAdv",
        imgSrc: "./images/servAdv-img.jpg",
        imgAlt: "Advertise Services",
        icon: "./images/ico-adv.png",
    },
    {
        title: "التغليف والعلب",
        description: "مما لا شك فيه أن التغليف الجيد والمبتكر لمنتجك ينقله إلى مستوى آخر، نحن معك لنساعدك لخروج منتجك بأفضل صورة ممكنة لدينا آليات كاملة لتصميم وطباعة وتنفيذ تغليف بأفكار جديدة رائعة",
        btnCaption: "طلب عرض سعر",
        btnLink: "servPackage",
        imgSrc: "./images/servPackage-img.jpg",
        imgAlt: "Packaging Services",
        icon: "./images/ico-package.png",
    },
    {
        title: "لافتات دعائية",
        description: "يمكننا تنفيذ اللافتات الخارجية بكل أنواعها وأشكالها بما يتنساب مع نشاطك وبأفضل الوسائل والخامات التي تظهرك بشكل مميز ورائع",
        btnCaption: "طلب عرض سعر",
        btnLink: "servBanner",
        imgSrc: "./images/servBanner-img.jpg",
        imgAlt: "Banners Services",
        icon: "./images/ico-banners.png",
    },
    {
        title: "التصوير",
        description: "التصوير الجيد من اهم وسائل نجاح ظهور منتجك ومحتواك بشكل مميزلدينا فريق محترف من المصورين والمخرجين ومتخصصين الميديا لخروج محتواك بشكل مميز بداية من تجهيز الإسكربت ومروراً بالسينريو وصولا للتصوير بأحدث الكاميرات والأدوات الخاصة بالتصوير",
        btnCaption: "طلب عرض سعر",
        btnLink: "servPhoto",
        imgSrc: "./images/servPhoto-img.jpg",
        imgAlt: "Photography Services",
        icon: "./images/ico-photo.png",
    },
    {
        title: "تنظيم معارض",
        description: "جناحك في المعرض يمثلك بشكل كامل حيث مشاركتك في المعارض يمثل احتكاك مباشر بالعملاء المحتملين وأقرانك في المجال، لذلك نحن في انتظارك لنبني لك تصور الجناح بداية من تصميم الجناح مودلينج 3D إلى تطبيقه وتنفيذه بكل دقة، من خلال تنفيذ مميز ورائع لما سيتم تصميمه",
        btnCaption: "طلب عرض سعر",
        btnLink: "servShows",
        imgSrc: "./images/servShows-img.jpg",
        imgAlt: "Shows Services",
        icon: "./images/ico-shows.png",
    },
    {
        title: "البروفايل",
        description: "بروفايل الشركات: بوابة للإبداع والتميز، حيث تتجسد رؤيتنا وقيمنا. اكتشفوا تاريخنا ومنتجاتنا الابتكارية وشراكاتنا الملهمة لتحقيق النجاح المشترك",
        btnCaption: "طلب عرض سعر",
        btnLink: "servProfile",
        imgSrc: "./images/servProfile-img.jpg",
        imgAlt: "Profile Services",
        icon: "./images/ico-profile.png",
    },
    {
        title: "مكتبة مسار",
        description: "تمثل مكتبة مسار منصة رائعة لخدمة القارئ بكل تنوعات طلباته، حيث توفر لكم كتب كثيرة في مجالات متعددة يمكن طلبها من خلال المنصة، لتصلكم في وقت قياسي وبأي كمية، ونعدكم أن نثري المنصة بكتب مميزة في كل المجالات وأن نكون على عهدنا بتوفيرها لكم بجودة رائعة أينما كنتم",
        btnCaption: "تصفح المكتبة",
        btnLink: "servLib",
        imgSrc: "./images/servLib-img.jpg",
        imgAlt: "Liberary Services",
        icon: "./images/ico-lib.png",
    },
]

export { ServiceData };